// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jctUd3OniE5mCZqQZc2WU2MiACXQXEU',
    appId: '1:712902093149:web:03cd3b57829c1016fee0b4',
    messagingSenderId: '712902093149',
    projectId: 'medslots-378c8',
    authDomain: 'medslots-378c8.firebaseapp.com',
    storageBucket: 'medslots-378c8.firebasestorage.app',
    measurementId: 'G-KBSNC0FF58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvLsPKbZgD0DveTEpkUCZGqD2ZzzkDFKs',
    appId: '1:712902093149:android:729246148f5e3683fee0b4',
    messagingSenderId: '712902093149',
    projectId: 'medslots-378c8',
    storageBucket: 'medslots-378c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3x1KACbcTV1gQ06WmFGp6AM4QSOlxDI',
    appId: '1:712902093149:ios:832ec169e04350c4fee0b4',
    messagingSenderId: '712902093149',
    projectId: 'medslots-378c8',
    storageBucket: 'medslots-378c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterMedslots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3x1KACbcTV1gQ06WmFGp6AM4QSOlxDI',
    appId: '1:712902093149:ios:832ec169e04350c4fee0b4',
    messagingSenderId: '712902093149',
    projectId: 'medslots-378c8',
    storageBucket: 'medslots-378c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterMedslots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jctUd3OniE5mCZqQZc2WU2MiACXQXEU',
    appId: '1:712902093149:web:262540d993be67b1fee0b4',
    messagingSenderId: '712902093149',
    projectId: 'medslots-378c8',
    authDomain: 'medslots-378c8.firebaseapp.com',
    storageBucket: 'medslots-378c8.firebasestorage.app',
    measurementId: 'G-VSN7EXGDDH',
  );
}

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// ...

// await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
// );
